# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "Essence de Cardamone")
Ingredient.create(name: "Extrait de vanille")
Ingredient.create(name: "Fleur d'oranger")
Ingredient.create(name: "Fleur de sel")
Ingredient.create(name: "Glaçons")
Ingredient.create(name: "Glace à la vanille")
Ingredient.create(name: "Glace concassée")
Ingredient.create(name: "Glace de Café")
Ingredient.create(name: "Glace de Marron")
Ingredient.create(name: "Glace Pilée")
Ingredient.create(name: "Miel")
Ingredient.create(name: "Oeuf")
Ingredient.create(name: "Puré De Marrons Glacés")
Ingredient.create(name: "Sauce Worcesterhire")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "fraise tagada")
Ingredient.create(name: "Chocolat")
Ingredient.create(name: "Biscuit Speculoos")
Ingredient.create(name: "Glace au chocolat")
Ingredient.create(name: "Baton de cannelle")
Ingredient.create(name: "Gingembre")
Ingredient.create(name: "Muscade")
Ingredient.create(name: "Gousse de vanille")
Ingredient.create(name: "Piment de cayenne")
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "Thé")
Ingredient.create(name: "Cacao en poudre")
Ingredient.create(name: "Café en grain")
Ingredient.create(name: "Café chaud")

Ingredient.create(name: "Campari")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Rhum ambré")
Ingredient.create(name: "Vermouth")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Whisky")
Ingredient.create(name: "Eau")
Ingredient.create(name: "Eau gazeuse")
Ingredient.create(name: "Jus d'ananas")
Ingredient.create(name: "Jus de betterave")
Ingredient.create(name: "Jus de carotte")
Ingredient.create(name: "Jus de citron")
Ingredient.create(name: "Jus de fraise")
Ingredient.create(name: "Jus de cranberry")
Ingredient.create(name: "Jus de cassis")
Ingredient.create(name: "Jus d'orange")
Ingredient.create(name: "Jus de Goyave")
Ingredient.create(name: "Jus de fruit de la passion")
Ingredient.create(name: "Jus de fruit exotique")
Ingredient.create(name: "Jus de tomate")
Ingredient.create(name: "Jus de raisins")
Ingredient.create(name: "Jus de mangues")
Ingredient.create(name: "Nectar d'abricot")
Ingredient.create(name: "Nectar de bananes")
Ingredient.create(name: "Sirop d'anis")
Ingredient.create(name: "Lime cordial")
Ingredient.create(name: "Ice Tea")
Ingredient.create(name: "Coca Cola")
Ingredient.create(name: "Tonic")
Ingredient.create(name: "Red Bull")
Ingredient.create(name: "Orangina")
Ingredient.create(name: "Schweppes Agrum")
Ingredient.create(name: "Limonade")
